"""
MAX POTENTIAL PRESETS - generated by optimize.py
These are aggressive but still hard-capped for $10 survival
"""
from config import BotConfig, PRESETS, RiskConfig, StrategyConfig, ExitConfig, ExecutionConfig

# EURUSD_M5_MAX: +35% in 5 days synthetic, PF 2.99 WR 85.7% DD 5.1% (vs baseline +7.5% PF 1.96)
PRESETS_MAX_EUR = BotConfig(
    execution=ExecutionConfig(symbol="EURUSD", max_spread_points=20, start_hour=7, end_hour=17, min_bars_between_trades=2),
    strategy=StrategyConfig(ema_fast=9, ema_slow=21, rsi_period=14, rsi_buy_min=50, rsi_buy_max=72, rsi_sell_min=32, rsi_sell_max=48, atr_period=14, atr_sl_mult=2.2, atr_tp_mult=1.2, min_atr_points=40, max_atr_points=1200),
    risk=RiskConfig(risk_percent=2.2, max_lot=0.05, max_daily_loss_pct=5.0, daily_target_pct=5.0, max_trades_per_day=18, max_consecutive_losses=3, cooldown_minutes=30),
    exit=ExitConfig(breakeven_trigger_points=100, breakeven_plus_points=50, trailing_start_points=120, trailing_step_points=60, max_hold_minutes=90)
)

# XAUUSD MAX: derived from XAU best (+20% in 5 days, PF2.62 WR82.9%): EMA 8/26 RSI 55-65/35-52 ATR 1.8/0.9 risk2.0% trail90/40 hold150
PRESETS_MAX_XAU = BotConfig(
    execution=ExecutionConfig(symbol="XAUUSD", max_spread_points=350, start_hour=7, end_hour=17),
    strategy=StrategyConfig(ema_fast=8, ema_slow=26, rsi_period=14, rsi_buy_min=55, rsi_buy_max=65, rsi_sell_min=35, rsi_sell_max=52, atr_period=14, atr_sl_mult=1.8, atr_tp_mult=0.9, min_atr_points=60, max_atr_points=2000),
    risk=RiskConfig(risk_percent=2.0, max_lot=0.03, max_daily_loss_pct=5.0, daily_target_pct=6.0, max_trades_per_day=15),
    exit=ExitConfig(breakeven_trigger_points=120, breakeven_plus_points=60, trailing_start_points=90, trailing_step_points=40, max_hold_minutes=150)
)

# GBPUSD MAX: no improvement over baseline, but we boost risk slightly and London session
PRESETS_MAX_GBP = BotConfig(
    execution=ExecutionConfig(symbol="GBPUSD", max_spread_points=25, start_hour=7, end_hour=17),
    strategy=StrategyConfig(timeframe="M1", ema_fast=8, ema_slow=21, rsi_period=12, rsi_buy_min=48, rsi_buy_max=68, rsi_sell_min=32, rsi_sell_max=50, atr_period=10, atr_sl_mult=1.5, atr_tp_mult=1.2, min_atr_points=40, max_atr_points=800),
    risk=RiskConfig(risk_percent=1.8, max_lot=0.05, max_daily_loss_pct=5.0, daily_target_pct=5.0, max_trades_per_day=18),
    exit=ExitConfig(breakeven_trigger_points=90, breakeven_plus_points=50, trailing_start_points=100, trailing_step_points=50, max_hold_minutes=90)
)

# V75 MAX: aggressive for synthetics 24/7
PRESETS_MAX_V75 = BotConfig(
    execution=ExecutionConfig(symbol="Volatility 75 Index", max_spread_points=700, start_hour=0, end_hour=23),
    strategy=StrategyConfig(timeframe="M1", ema_fast=7, ema_slow=20, rsi_period=10, rsi_buy_min=48, rsi_buy_max=70, rsi_sell_min=30, rsi_sell_max=52, atr_period=10, atr_sl_mult=1.8, atr_tp_mult=1.4, min_atr_points=150, max_atr_points=60000),
    risk=RiskConfig(risk_percent=1.5, max_lot=0.02, max_daily_loss_pct=5.0, daily_target_pct=6.0, max_trades_per_day=20),
    exit=ExitConfig(breakeven_trigger_points=100, breakeven_plus_points=50, trailing_start_points=120, trailing_step_points=60, max_hold_minutes=60)
)
